### ISSUE TITLE
demo page is inoperative due to github mime-type

### ISSUE THREAD

**Issue by mdaniel** [mtkopone/zelect#9]
As GitHub mentioned [on their blog](https://github.com/blog/1482-heads-up-nosniff-header-support-coming-to-chrome-and-firefox), they have put a stop to hotlinking to the raw asset.

Thus, in modern browsers the [zelect demo page](http://mtkopone.github.io/zelect/) is now inoperative.

**Comment by rafaelverger** [comment]
Yep.. here is the error in chrome:
Refused to execute script from 'http://raw.github.com/mtkopone/zelect/master/zelect.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. 

But it works if you call via jQuery.getScript: `$.getScript('http://raw.github.com/mtkopone/zelect/master/zelect.js')`

**Comment by mtkopone** [comment]
I don't think using $.getScript was what the github guys were after...

Fixed by copying zelect.js to gh-pages branch.

Sorry about the slow response times to these issues, I'm on paternity leave, and the kid is taking up most of my CPU cycles :)

**Comment by rafaelverger** [comment]
@mtkopone , i'm sure that `$.getScript` wasn't the best solution, it was just to make the demo page working in a fast way..
